// Package catalog20220401 provides primitives to interact the openapi HTTP API.
//
// Code generated by go-sdk-codegen DO NOT EDIT.
package catalog20220401

import (
	"encoding/json"
	"fmt"

	openapi_types "github.com/amzapi/selling-partner-api-sdk/pkg/types"
	"github.com/pkg/errors"
)

// BrandRefinement defines model for BrandRefinement.
type BrandRefinement struct {

	// The brand name that you can use to refine your search.
	BrandName string `json:"brandName"`

	// The estimated number of results that would be returned if you refine your search by the specified `brandName`.
	NumberOfResults int `json:"numberOfResults"`
}

// ClassificationRefinement defines model for ClassificationRefinement.
type ClassificationRefinement struct {

	// The identifier of the classification that you can use to refine your search.
	ClassificationId string `json:"classificationId"`

	// Display name for the classification.
	DisplayName string `json:"displayName"`

	// The estimated number of results that would be returned if you refine your search by the specified `classificationId`.
	NumberOfResults int `json:"numberOfResults"`
}

// Dimension defines model for Dimension.
type Dimension struct {

	// Unit of measurement for the dimension value.
	Unit *string `json:"unit,omitempty"`

	// Numeric value of the dimension.
	Value *float32 `json:"value,omitempty"`
}

// Dimensions defines model for Dimensions.
type Dimensions struct {

	// The value of an individual dimension for an Amazon catalog item or item package.
	Height *Dimension `json:"height,omitempty"`

	// The value of an individual dimension for an Amazon catalog item or item package.
	Length *Dimension `json:"length,omitempty"`

	// The value of an individual dimension for an Amazon catalog item or item package.
	Weight *Dimension `json:"weight,omitempty"`

	// The value of an individual dimension for an Amazon catalog item or item package.
	Width *Dimension `json:"width,omitempty"`
}

// Error defines model for Error.
type Error struct {

	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`

	// Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// A message that describes the error condition.
	Message string `json:"message"`
}

// ErrorList defines model for ErrorList.
type ErrorList struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors []Error `json:"errors"`
}

// Item defines model for Item.
type Item struct {

	// The unique identifier of an item in the Amazon catalog.
	Asin ItemAsin `json:"asin"`

	// A JSON object containing structured item attribute data that is keyed by attribute name. Catalog item attributes conform to the related Amazon product type definitions that you can get from the [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/reference/product-type-definitions-v2020-09-01).
	Attributes *ItemAttributes `json:"attributes,omitempty"`

	// An array of classifications (browse nodes) that is associated with the item in the Amazon catalog, grouped by `marketplaceId`.
	Classifications *ItemBrowseClassifications `json:"classifications,omitempty"`

	// An array of dimensions that are associated with the item in the Amazon catalog, grouped by `marketplaceId`.
	Dimensions *ItemDimensions `json:"dimensions,omitempty"`

	// Identifiers associated with the item in the Amazon catalog, such as UPC and EAN identifiers.
	Identifiers *ItemIdentifiers `json:"identifiers,omitempty"`

	// The images for an item in the Amazon catalog.
	Images *ItemImages `json:"images,omitempty"`

	// Product types that are associated with the Amazon catalog item.
	ProductTypes *ItemProductTypes `json:"productTypes,omitempty"`

	// Relationships grouped by `marketplaceId` for an Amazon catalog item (for example, variations).
	Relationships *ItemRelationships `json:"relationships,omitempty"`

	// Sales ranks of an Amazon catalog item.
	SalesRanks *ItemSalesRanks `json:"salesRanks,omitempty"`

	// Summaries of Amazon catalog items.
	Summaries *ItemSummaries `json:"summaries,omitempty"`

	// The vendor details that are associated with an Amazon catalog item. Vendor details are only available to vendors.
	VendorDetails *ItemVendorDetails `json:"vendorDetails,omitempty"`
}

// ItemAsin defines model for ItemAsin.
type ItemAsin string

// ItemAttributes defines model for ItemAttributes.
type ItemAttributes struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ItemBrowseClassification defines model for ItemBrowseClassification.
type ItemBrowseClassification struct {

	// Identifier of the classification.
	ClassificationId string `json:"classificationId"`

	// Display name for the classification.
	DisplayName string `json:"displayName"`

	// Classification (browse node) for an Amazon catalog item.
	Parent *ItemBrowseClassification `json:"parent,omitempty"`
}

// ItemBrowseClassifications defines model for ItemBrowseClassifications.
type ItemBrowseClassifications []ItemBrowseClassificationsByMarketplace

// ItemBrowseClassificationsByMarketplace defines model for ItemBrowseClassificationsByMarketplace.
type ItemBrowseClassificationsByMarketplace struct {

	// Classifications (browse nodes) that are associated with the item in the Amazon catalog.
	Classifications *[]ItemBrowseClassification `json:"classifications,omitempty"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
}

// ItemClassificationSalesRank defines model for ItemClassificationSalesRank.
type ItemClassificationSalesRank struct {

	// Identifier of the classification that is associated with the sales rank.
	ClassificationId string `json:"classificationId"`

	// Corresponding Amazon retail website URL for the sales category.
	Link *string `json:"link,omitempty"`

	// Sales rank.
	Rank int `json:"rank"`

	// Name of the sales rank.
	Title string `json:"title"`
}

// ItemContributor defines model for ItemContributor.
type ItemContributor struct {

	// Role of an individual contributor in the creation of an item, such as author or actor.
	Role ItemContributorRole `json:"role"`

	// Name of the contributor, such as `Jane Austen`.
	Value string `json:"value"`
}

// ItemContributorRole defines model for ItemContributorRole.
type ItemContributorRole struct {

	// Display name of the role in the requested locale, such as `Author` or `Actor`.
	DisplayName *string `json:"displayName,omitempty"`

	// Role value for the Amazon catalog item, such as `author` or `actor`.
	Value string `json:"value"`
}

// ItemDimensions defines model for ItemDimensions.
type ItemDimensions []ItemDimensionsByMarketplace

// ItemDimensionsByMarketplace defines model for ItemDimensionsByMarketplace.
type ItemDimensionsByMarketplace struct {

	// Dimensions of an Amazon catalog item or item in its packaging.
	Item *Dimensions `json:"item,omitempty"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`

	// Dimensions of an Amazon catalog item or item in its packaging.
	Package *Dimensions `json:"package,omitempty"`
}

// ItemDisplayGroupSalesRank defines model for ItemDisplayGroupSalesRank.
type ItemDisplayGroupSalesRank struct {

	// Corresponding Amazon retail website URL for the sales rank.
	Link *string `json:"link,omitempty"`

	// Sales rank.
	Rank int `json:"rank"`

	// Name of the sales rank.
	Title string `json:"title"`

	// Name of the website display group that is associated with the sales rank
	WebsiteDisplayGroup string `json:"websiteDisplayGroup"`
}

// ItemIdentifier defines model for ItemIdentifier.
type ItemIdentifier struct {

	// Identifier of the item.
	Identifier string `json:"identifier"`

	// Type of identifier, such as UPC, EAN, or ISBN.
	IdentifierType string `json:"identifierType"`
}

// ItemIdentifiers defines model for ItemIdentifiers.
type ItemIdentifiers []ItemIdentifiersByMarketplace

// ItemIdentifiersByMarketplace defines model for ItemIdentifiersByMarketplace.
type ItemIdentifiersByMarketplace struct {

	// Identifiers associated with the item in the Amazon catalog for the indicated `marketplaceId`.
	Identifiers []ItemIdentifier `json:"identifiers"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).identifier.
	MarketplaceId string `json:"marketplaceId"`
}

// ItemImage defines model for ItemImage.
type ItemImage struct {

	// Height of the image in pixels.
	Height int `json:"height"`

	// URL for the image.
	Link string `json:"link"`

	// Variant of the image, such as `MAIN` or `PT01`.
	Variant string `json:"variant"`

	// Width of the image in pixels.
	Width int `json:"width"`
}

// ItemImages defines model for ItemImages.
type ItemImages []ItemImagesByMarketplace

// ItemImagesByMarketplace defines model for ItemImagesByMarketplace.
type ItemImagesByMarketplace struct {

	// Images for an item in the Amazon catalog, grouped by `marketplaceId`.
	Images []ItemImage `json:"images"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
}

// ItemProductTypeByMarketplace defines model for ItemProductTypeByMarketplace.
type ItemProductTypeByMarketplace struct {

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId *string `json:"marketplaceId,omitempty"`

	// Name of the product type that is associated with the Amazon catalog item.
	ProductType *string `json:"productType,omitempty"`
}

// ItemProductTypes defines model for ItemProductTypes.
type ItemProductTypes []ItemProductTypeByMarketplace

// ItemRelationship defines model for ItemRelationship.
type ItemRelationship struct {

	// ASINs of the related items that are children of this item.
	ChildAsins *[]string `json:"childAsins,omitempty"`

	// ASINs of the related items that are parents of this item.
	ParentAsins *[]string `json:"parentAsins,omitempty"`

	// Type of relationship.
	Type string `json:"type"`

	// The variation theme is a list of Amazon catalog item attributes that define the variation family.
	VariationTheme *ItemVariationTheme `json:"variationTheme,omitempty"`
}

// ItemRelationships defines model for ItemRelationships.
type ItemRelationships []ItemRelationshipsByMarketplace

// ItemRelationshipsByMarketplace defines model for ItemRelationshipsByMarketplace.
type ItemRelationshipsByMarketplace struct {

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`

	// Relationships for the item.
	Relationships []ItemRelationship `json:"relationships"`
}

// ItemSalesRanks defines model for ItemSalesRanks.
type ItemSalesRanks []ItemSalesRanksByMarketplace

// ItemSalesRanksByMarketplace defines model for ItemSalesRanksByMarketplace.
type ItemSalesRanksByMarketplace struct {

	// Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by classification.
	ClassificationRanks *[]ItemClassificationSalesRank `json:"classificationRanks,omitempty"`

	// Sales ranks of an Amazon catalog item for a `marketplaceId`, grouped by website display group.
	DisplayGroupRanks *[]ItemDisplayGroupSalesRank `json:"displayGroupRanks,omitempty"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
}

// ItemSearchResults defines model for ItemSearchResults.
type ItemSearchResults struct {

	// A list of items from the Amazon catalog.
	Items []Item `json:"items"`

	// For searches that are based on `identifiers`, `numberOfResults` is the total number of Amazon catalog items found. For searches that are based on `keywords`, `numberOfResults` is the estimated total number of Amazon catalog items that are matched by the search query. Only results up to the page count limit are returned per request regardless of the number found.
	//
	// **Note:** The maximum number of items (ASINs) that can be returned and paged through is 1,000.
	NumberOfResults int `json:"numberOfResults"`

	// Pagination occurs when a request produces a response that exceeds the `pageSize`. This means that the response is divided into individual pages. To retrieve the next page or the previous page of results, you must pass the `nextToken` value or the `previousToken` value as the `pageToken` parameter in the next request. There is no `nextToken` in the pagination object on the last page.
	Pagination *Pagination `json:"pagination,omitempty"`

	// Optional fields that you can use to refine your search results.
	Refinements *Refinements `json:"refinements,omitempty"`
}

// ItemSummaries defines model for ItemSummaries.
type ItemSummaries []ItemSummaryByMarketplace

// ItemSummaryByMarketplace defines model for ItemSummaryByMarketplace.
type ItemSummaryByMarketplace struct {

	// When `true`, the Amazon catalog item is intended for an adult audience or is sexual in nature.
	AdultProduct *bool `json:"adultProduct,omitempty"`

	// When `true`, the Amazon catalog item is autographed.
	Autographed *bool `json:"autographed,omitempty"`

	// Name of the brand that is associated with the Amazon catalog item.
	Brand *string `json:"brand,omitempty"`

	// Classification (browse node) for an Amazon catalog item.
	BrowseClassification *ItemBrowseClassification `json:"browseClassification,omitempty"`

	// The color that is associated with the Amazon catalog item.
	Color *string `json:"color,omitempty"`

	// Individual contributors to the creation of the item, such as the authors or actors.
	Contributors *[]ItemContributor `json:"contributors,omitempty"`

	// Classification type that is associated with the Amazon catalog item.
	ItemClassification *string `json:"itemClassification,omitempty"`

	// The name that is associated with the Amazon catalog item.
	ItemName *string `json:"itemName,omitempty"`

	// The name of the manufacturer that is associated with the Amazon catalog item.
	Manufacturer *string `json:"manufacturer,omitempty"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`

	// When true, the item is classified as memorabilia.
	Memorabilia *bool `json:"memorabilia,omitempty"`

	// The model number that is associated with the Amazon catalog item.
	ModelNumber *string `json:"modelNumber,omitempty"`

	// The quantity of the Amazon catalog item within one package.
	PackageQuantity *int `json:"packageQuantity,omitempty"`

	// The part number that is associated with the Amazon catalog item.
	PartNumber *string `json:"partNumber,omitempty"`

	// The earliest date on which the Amazon catalog item can be shipped to customers.
	ReleaseDate *openapi_types.Date `json:"releaseDate,omitempty"`

	// The name of the size of the Amazon catalog item.
	Size *string `json:"size,omitempty"`

	// The name of the style that is associated with the Amazon catalog item.
	Style *string `json:"style,omitempty"`

	// When true, the Amazon catalog item is eligible for trade-in.
	TradeInEligible *bool `json:"tradeInEligible,omitempty"`

	// The identifier of the website display group that is associated with the Amazon catalog item.
	WebsiteDisplayGroup *string `json:"websiteDisplayGroup,omitempty"`

	// The display name of the website display group that is associated with the Amazon catalog item.
	WebsiteDisplayGroupName *string `json:"websiteDisplayGroupName,omitempty"`
}

// ItemVariationTheme defines model for ItemVariationTheme.
type ItemVariationTheme struct {

	// Names of the Amazon catalog item attributes that are associated with the variation theme.
	Attributes *[]string `json:"attributes,omitempty"`

	// Variation theme that indicates the combination of Amazon catalog item attributes that define the variation family.
	Theme *string `json:"theme,omitempty"`
}

// ItemVendorDetails defines model for ItemVendorDetails.
type ItemVendorDetails []ItemVendorDetailsByMarketplace

// ItemVendorDetailsByMarketplace defines model for ItemVendorDetailsByMarketplace.
type ItemVendorDetailsByMarketplace struct {

	// The brand code that is associated with an Amazon catalog item.
	BrandCode *string `json:"brandCode,omitempty"`

	// The manufacturer code that is associated with an Amazon catalog item.
	ManufacturerCode *string `json:"manufacturerCode,omitempty"`

	// The parent vendor code of the manufacturer code.
	ManufacturerCodeParent *string `json:"manufacturerCodeParent,omitempty"`

	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`

	// The product category or subcategory that is associated with an Amazon catalog item.
	ProductCategory *ItemVendorDetailsCategory `json:"productCategory,omitempty"`

	// The product group that is associated with an Amazon catalog item.
	ProductGroup *string `json:"productGroup,omitempty"`

	// The product category or subcategory that is associated with an Amazon catalog item.
	ProductSubcategory *ItemVendorDetailsCategory `json:"productSubcategory,omitempty"`

	// The replenishment category that is associated with an Amazon catalog item.
	ReplenishmentCategory *string `json:"replenishmentCategory,omitempty"`
}

// ItemVendorDetailsCategory defines model for ItemVendorDetailsCategory.
type ItemVendorDetailsCategory struct {

	// The display name of the product category or subcategory.
	DisplayName *string `json:"displayName,omitempty"`

	// The code that identifies the product category or subcategory.
	Value *string `json:"value,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {

	// A token that you can use to retrieve the next page.
	NextToken *string `json:"nextToken,omitempty"`

	// A token that you can use to retrieve the previous page.
	PreviousToken *string `json:"previousToken,omitempty"`
}

// Refinements defines model for Refinements.
type Refinements struct {

	// A list of brands you can use to refine your search.
	Brands []BrandRefinement `json:"brands"`

	// A list of classifications you can use to refine your search.
	Classifications []ClassificationRefinement `json:"classifications"`
}

// SearchCatalogItemsParams defines parameters for SearchCatalogItems.
type SearchCatalogItemsParams struct {

	// A comma-delimited list of product identifiers that you can use to search the Amazon catalog. **Note:** You cannot include `identifiers` and `keywords` in the same request.
	Identifiers *[]string `json:"identifiers,omitempty"`

	// The type of product identifiers that you can use to search the Amazon catalog. **Note:** `identifiersType` is required when `identifiers` is in the request.
	IdentifiersType *string `json:"identifiersType,omitempty"`

	// A comma-delimited list of Amazon marketplace identifiers. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceIds []string `json:"marketplaceIds"`

	// A comma-delimited list of datasets to include in the response.
	IncludedData *[]string `json:"includedData,omitempty"`

	// The locale for which you want to retrieve localized summaries. Defaults to the primary locale of the marketplace.
	Locale *string `json:"locale,omitempty"`

	// A selling partner identifier, such as a seller account or vendor code. **Note:** Required when `identifiersType` is `SKU`.
	SellerId *string `json:"sellerId,omitempty"`

	// A comma-delimited list of keywords that you can use to search the Amazon catalog. **Note:** You cannot include `keywords` and `identifiers` in the same request.
	Keywords *[]string `json:"keywords,omitempty"`

	// A comma-delimited list of brand names that you can use to limit the search in queries based on `keywords`. **Note:** Cannot be used with `identifiers`.
	BrandNames *[]string `json:"brandNames,omitempty"`

	// A comma-delimited list of classification identifiers that you can use to limit the search in queries based on `keywords`. **Note:** Cannot be used with `identifiers`.
	ClassificationIds *[]string `json:"classificationIds,omitempty"`

	// The number of results to include on each page.
	PageSize *int `json:"pageSize,omitempty"`

	// A token that you can use to fetch a specific page when there are multiple pages of results.
	PageToken *string `json:"pageToken,omitempty"`

	// The language of the keywords that are included in queries based on `keywords`. Defaults to the primary locale of the marketplace. **Note:** Cannot be used with `identifiers`.
	KeywordsLocale *string `json:"keywordsLocale,omitempty"`
}

// GetCatalogItemParams defines parameters for GetCatalogItem.
type GetCatalogItemParams struct {

	// A comma-delimited list of Amazon marketplace identifiers. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceIds []string `json:"marketplaceIds"`

	// A comma-delimited list of datasets to include in the response.
	IncludedData *[]string `json:"includedData,omitempty"`

	// The locale for which you want to retrieve localized summaries. Defaults to the primary locale of the marketplace.
	Locale *string `json:"locale,omitempty"`
}

// Getter for additional properties for ItemAttributes. Returns the specified
// element and whether it was found
func (a ItemAttributes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ItemAttributes
func (a *ItemAttributes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ItemAttributes to handle AdditionalProperties
func (a *ItemAttributes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ItemAttributes to handle AdditionalProperties
func (a ItemAttributes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}
