// Package productPricing20220501 provides primitives to interact the openapi HTTP API.
//
// Code generated by go-sdk-codegen DO NOT EDIT.
package productPricing20220501

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	runt "runtime"
	"strings"
)

// RequestBeforeFn  is the function signature for the RequestBefore callback function
type RequestBeforeFn func(ctx context.Context, req *http.Request) error

// ResponseAfterFn  is the function signature for the ResponseAfter callback function
type ResponseAfterFn func(ctx context.Context, rsp *http.Response) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Endpoint string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A callback for modifying requests which are generated before sending over
	// the network.
	RequestBefore RequestBeforeFn

	// A callback for modifying response which are generated before sending over
	// the network.
	ResponseAfter ResponseAfterFn

	// The user agent header identifies your application, its version number, and the platform and programming language you are using.
	// You must include a user agent header in each request submitted to the sales partner API.
	UserAgent string
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(endpoint string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Endpoint: endpoint,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the endpoint URL always has a trailing slash
	if !strings.HasSuffix(client.Endpoint, "/") {
		client.Endpoint += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = http.DefaultClient
	}
	// setting the default useragent
	if client.UserAgent == "" {
		client.UserAgent = fmt.Sprintf("selling-partner-api-sdk/v1.0 (Language=%s; Platform=%s-%s)", strings.Replace(runt.Version(), "go", "go/", -1), runt.GOOS, runt.GOARCH)
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithUserAgent set up useragent
// add user agent to every request automatically
func WithUserAgent(userAgent string) ClientOption {
	return func(c *Client) error {
		c.UserAgent = userAgent
		return nil
	}
}

// WithRequestBefore allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestBefore(fn RequestBeforeFn) ClientOption {
	return func(c *Client) error {
		c.RequestBefore = fn
		return nil
	}
}

// WithResponseAfter allows setting up a callback function, which will be
// called right after get response the request. This can be used to log.
func WithResponseAfter(fn ResponseAfterFn) ClientOption {
	return func(c *Client) error {
		c.ResponseAfter = fn
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCompetitiveSummary request  with any body
	GetCompetitiveSummaryWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	GetCompetitiveSummary(ctx context.Context, body GetCompetitiveSummaryJSONRequestBody) (*http.Response, error)

	// GetFeaturedOfferExpectedPriceBatch request  with any body
	GetFeaturedOfferExpectedPriceBatchWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	GetFeaturedOfferExpectedPriceBatch(ctx context.Context, body GetFeaturedOfferExpectedPriceBatchJSONRequestBody) (*http.Response, error)
}

func (c *Client) GetCompetitiveSummaryWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewGetCompetitiveSummaryRequestWithBody(c.Endpoint, contentType, body)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)
	req.Header.Set("User-Agent", c.UserAgent)
	if c.RequestBefore != nil {
		err = c.RequestBefore(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	rsp, err := c.Client.Do(req)
	if err != nil {
		return nil, err
	}

	if c.ResponseAfter != nil {
		err = c.ResponseAfter(ctx, rsp)
		if err != nil {
			return nil, err
		}
	}
	return rsp, nil
}

func (c *Client) GetCompetitiveSummary(ctx context.Context, body GetCompetitiveSummaryJSONRequestBody) (*http.Response, error) {
	req, err := NewGetCompetitiveSummaryRequest(c.Endpoint, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestBefore != nil {
		err = c.RequestBefore(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) GetFeaturedOfferExpectedPriceBatchWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewGetFeaturedOfferExpectedPriceBatchRequestWithBody(c.Endpoint, contentType, body)
	if err != nil {
		return nil, err
	}

	req = req.WithContext(ctx)
	req.Header.Set("User-Agent", c.UserAgent)
	if c.RequestBefore != nil {
		err = c.RequestBefore(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	rsp, err := c.Client.Do(req)
	if err != nil {
		return nil, err
	}

	if c.ResponseAfter != nil {
		err = c.ResponseAfter(ctx, rsp)
		if err != nil {
			return nil, err
		}
	}
	return rsp, nil
}

func (c *Client) GetFeaturedOfferExpectedPriceBatch(ctx context.Context, body GetFeaturedOfferExpectedPriceBatchJSONRequestBody) (*http.Response, error) {
	req, err := NewGetFeaturedOfferExpectedPriceBatchRequest(c.Endpoint, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestBefore != nil {
		err = c.RequestBefore(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

// NewGetCompetitiveSummaryRequest calls the generic GetCompetitiveSummary builder with application/json body
func NewGetCompetitiveSummaryRequest(endpoint string, body GetCompetitiveSummaryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetCompetitiveSummaryRequestWithBody(endpoint, "application/json", bodyReader)
}

// NewGetCompetitiveSummaryRequestWithBody generates requests for GetCompetitiveSummary with any type of body
func NewGetCompetitiveSummaryRequestWithBody(endpoint string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(endpoint)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/batches/products/pricing/2022-05-01/items/competitiveSummary")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// NewGetFeaturedOfferExpectedPriceBatchRequest calls the generic GetFeaturedOfferExpectedPriceBatch builder with application/json body
func NewGetFeaturedOfferExpectedPriceBatchRequest(endpoint string, body GetFeaturedOfferExpectedPriceBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetFeaturedOfferExpectedPriceBatchRequestWithBody(endpoint, "application/json", bodyReader)
}

// NewGetFeaturedOfferExpectedPriceBatchRequestWithBody generates requests for GetFeaturedOfferExpectedPriceBatch with any type of body
func NewGetFeaturedOfferExpectedPriceBatchRequestWithBody(endpoint string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(endpoint)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/batches/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(endpoint string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(endpoint, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Endpoint = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCompetitiveSummary request  with any body
	GetCompetitiveSummaryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetCompetitiveSummaryResp, error)

	GetCompetitiveSummaryWithResponse(ctx context.Context, body GetCompetitiveSummaryJSONRequestBody) (*GetCompetitiveSummaryResp, error)

	// GetFeaturedOfferExpectedPriceBatch request  with any body
	GetFeaturedOfferExpectedPriceBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetFeaturedOfferExpectedPriceBatchResp, error)

	GetFeaturedOfferExpectedPriceBatchWithResponse(ctx context.Context, body GetFeaturedOfferExpectedPriceBatchJSONRequestBody) (*GetFeaturedOfferExpectedPriceBatchResp, error)
}

type GetCompetitiveSummaryResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CompetitiveSummaryBatchResponse
	JSON400      *Errors
	JSON403      *Errors
	JSON404      *Errors
	JSON429      *Errors
	JSON500      *Errors
	JSON503      *Errors
}

// Status returns HTTPResponse.Status
func (r GetCompetitiveSummaryResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCompetitiveSummaryResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetFeaturedOfferExpectedPriceBatchResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetFeaturedOfferExpectedPriceBatchResponse
	JSON400      *Errors
	JSON401      *Errors
	JSON403      *Errors
	JSON404      *Errors
	JSON429      *Errors
	JSON500      *Errors
	JSON503      *Errors
}

// Status returns HTTPResponse.Status
func (r GetFeaturedOfferExpectedPriceBatchResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFeaturedOfferExpectedPriceBatchResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCompetitiveSummaryWithBodyWithResponse request with arbitrary body returning *GetCompetitiveSummaryResponse
func (c *ClientWithResponses) GetCompetitiveSummaryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetCompetitiveSummaryResp, error) {
	rsp, err := c.GetCompetitiveSummaryWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseGetCompetitiveSummaryResp(rsp)
}

func (c *ClientWithResponses) GetCompetitiveSummaryWithResponse(ctx context.Context, body GetCompetitiveSummaryJSONRequestBody) (*GetCompetitiveSummaryResp, error) {
	rsp, err := c.GetCompetitiveSummary(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseGetCompetitiveSummaryResp(rsp)
}

// GetFeaturedOfferExpectedPriceBatchWithBodyWithResponse request with arbitrary body returning *GetFeaturedOfferExpectedPriceBatchResponse
func (c *ClientWithResponses) GetFeaturedOfferExpectedPriceBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*GetFeaturedOfferExpectedPriceBatchResp, error) {
	rsp, err := c.GetFeaturedOfferExpectedPriceBatchWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseGetFeaturedOfferExpectedPriceBatchResp(rsp)
}

func (c *ClientWithResponses) GetFeaturedOfferExpectedPriceBatchWithResponse(ctx context.Context, body GetFeaturedOfferExpectedPriceBatchJSONRequestBody) (*GetFeaturedOfferExpectedPriceBatchResp, error) {
	rsp, err := c.GetFeaturedOfferExpectedPriceBatch(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseGetFeaturedOfferExpectedPriceBatchResp(rsp)
}

// ParseGetCompetitiveSummaryResp parses an HTTP response from a GetCompetitiveSummaryWithResponse call
func ParseGetCompetitiveSummaryResp(rsp *http.Response) (*GetCompetitiveSummaryResp, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetCompetitiveSummaryResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CompetitiveSummaryBatchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetFeaturedOfferExpectedPriceBatchResp parses an HTTP response from a GetFeaturedOfferExpectedPriceBatchWithResponse call
func ParseGetFeaturedOfferExpectedPriceBatchResp(rsp *http.Response) (*GetFeaturedOfferExpectedPriceBatchResp, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetFeaturedOfferExpectedPriceBatchResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetFeaturedOfferExpectedPriceBatchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Errors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
