// Package productPricing20220501 provides primitives to interact the openapi HTTP API.
//
// Code generated by go-sdk-codegen DO NOT EDIT.
package productPricing20220501

import (
	"encoding/json"
	"fmt"

	"github.com/pkg/errors"
)

// Asin defines model for Asin.
type Asin string

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {

	// Additional HTTP body information that is associated with an individual request within a batch.
	Body *HttpBody `json:"body,omitempty"`

	// A mapping of additional HTTP headers to send or receive for an individual request within a batch.
	Headers *HttpHeaders `json:"headers,omitempty"`

	// The HTTP method associated with an individual request within a batch.
	Method HttpMethod `json:"method"`

	// The URI associated with an individual request within a batch. For `FeaturedOfferExpectedPrice`, this is `/products/pricing/2022-05-01/offer/featuredOfferExpectedPrice`.
	Uri string `json:"uri"`
}

// BatchResponse defines model for BatchResponse.
type BatchResponse struct {

	// A mapping of additional HTTP headers to send or receive for an individual request within a batch.
	Headers HttpHeaders `json:"headers"`

	// The HTTP status line associated with the response for an individual request within a batch. For more information, refer to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).
	Status HttpStatusLine `json:"status"`
}

// CompetitiveSummaryBatchRequest defines model for CompetitiveSummaryBatchRequest.
type CompetitiveSummaryBatchRequest struct {

	// A batched list of `competitiveSummary` requests.
	Requests CompetitiveSummaryRequestList `json:"requests"`
}

// CompetitiveSummaryBatchResponse defines model for CompetitiveSummaryBatchResponse.
type CompetitiveSummaryBatchResponse struct {

	// The response list for the `competitiveSummaryBatch` operation.
	Responses CompetitiveSummaryResponseList `json:"responses"`
}

// CompetitiveSummaryIncludedData defines model for CompetitiveSummaryIncludedData.
type CompetitiveSummaryIncludedData string

// List of CompetitiveSummaryIncludedData
const (
	CompetitiveSummaryIncludedData_featuredBuyingOptions CompetitiveSummaryIncludedData = "featuredBuyingOptions"
	CompetitiveSummaryIncludedData_lowestPricedOffers    CompetitiveSummaryIncludedData = "lowestPricedOffers"
	CompetitiveSummaryIncludedData_referencePrices       CompetitiveSummaryIncludedData = "referencePrices"
	CompetitiveSummaryIncludedData_similarItems          CompetitiveSummaryIncludedData = "similarItems"
)

// CompetitiveSummaryRequest defines model for CompetitiveSummaryRequest.
type CompetitiveSummaryRequest struct {

	// The ASIN of the item.
	Asin Asin `json:"asin"`

	// The list of requested competitive pricing data for the product.
	IncludedData []CompetitiveSummaryIncludedData `json:"includedData"`

	// The list of `lowestPricedOffersInput` parameters that are used to build `lowestPricedOffers` in the response. This attribute is only valid if `lowestPricedOffers` is requested in `includedData`
	LowestPricedOffersInputs *[]LowestPricedOffersInput `json:"lowestPricedOffersInputs,omitempty"`

	// The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId MarketplaceId `json:"marketplaceId"`

	// The HTTP method associated with an individual request within a batch.
	Method HttpMethod `json:"method"`

	// The URI associated with the individual APIs that are called as part of the batch request.
	Uri HttpUri `json:"uri"`
}

// CompetitiveSummaryRequestList defines model for CompetitiveSummaryRequestList.
type CompetitiveSummaryRequestList []CompetitiveSummaryRequest

// CompetitiveSummaryResponse defines model for CompetitiveSummaryResponse.
type CompetitiveSummaryResponse struct {

	// The `competitiveSummaryResponse` body for a requested ASIN and `marketplaceId`.
	Body CompetitiveSummaryResponseBody `json:"body"`

	// The HTTP status line associated with the response for an individual request within a batch. For more information, refer to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).
	Status HttpStatusLine `json:"status"`
}

// CompetitiveSummaryResponseBody defines model for CompetitiveSummaryResponseBody.
type CompetitiveSummaryResponseBody struct {

	// The ASIN of the item.
	Asin Asin `json:"asin"`

	// A list of error responses that are returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// A list of featured buying options for the specified ASIN `marketplaceId` combination.
	FeaturedBuyingOptions *[]FeaturedBuyingOption `json:"featuredBuyingOptions,omitempty"`

	// A list of lowest priced offers for the specified ASIN `marketplaceId` combination.
	LowestPricedOffers *[]LowestPricedOffer `json:"lowestPricedOffers,omitempty"`

	// The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId MarketplaceId `json:"marketplaceId"`

	// A list of reference prices for the specified ASIN `marketplaceId` combination.
	ReferencePrices *[]ReferencePrice `json:"referencePrices,omitempty"`

	// A list of similar items for the specified ASIN `marketplaceId` combination.
	SimilarItems *[]SimilarItems `json:"similarItems,omitempty"`
}

// CompetitiveSummaryResponseList defines model for CompetitiveSummaryResponseList.
type CompetitiveSummaryResponseList []CompetitiveSummaryResponse

// Condition defines model for Condition.
type Condition string

// List of Condition
const (
	Condition_Club        Condition = "Club"
	Condition_Collectible Condition = "Collectible"
	Condition_New         Condition = "New"
	Condition_Refurbished Condition = "Refurbished"
	Condition_Used        Condition = "Used"
)

// Error defines model for Error.
type Error struct {

	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`

	// Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// A message that describes the error condition.
	Message string `json:"message"`
}

// ErrorList defines model for ErrorList.
type ErrorList []Error

// Errors defines model for Errors.
type Errors struct {

	// A list of error responses that are returned when a request is unsuccessful.
	Errors ErrorList `json:"errors"`
}

// FeaturedBuyingOption defines model for FeaturedBuyingOption.
type FeaturedBuyingOption struct {

	// The buying option type for the featured offer. `buyingOptionType` represents the buying options that a customer receives on the detail page, such as `B2B`, `Fresh`, and `Subscribe n Save`. `buyingOptionType` currently supports `NEW` as a value.
	BuyingOptionType string `json:"buyingOptionType"`

	// A list of segmented featured offers for the current buying option type. A segment can be considered as a group of regional contexts that all have the same featured offer. A regional context is a combination of factors such as customer type, region, or postal code and buying option.
	SegmentedFeaturedOffers []SegmentedFeaturedOffer `json:"segmentedFeaturedOffers"`
}

// FeaturedOffer defines model for FeaturedOffer.
type FeaturedOffer struct {

	// The condition of the item.
	Condition *Condition `json:"condition,omitempty"`

	// Identifies an offer from a particular seller for a specified ASIN.
	OfferIdentifier OfferIdentifier `json:"offerIdentifier"`

	// The schema for item's price information, including listing price, shipping price, and Amazon Points.
	Price *Price `json:"price,omitempty"`
}

// FeaturedOfferExpectedPrice defines model for FeaturedOfferExpectedPrice.
type FeaturedOfferExpectedPrice struct {

	// Currency type and monetary value schema to demonstrate pricing information.
	ListingPrice MoneyType `json:"listingPrice"`

	// The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points.
	Points *Points `json:"points,omitempty"`
}

// FeaturedOfferExpectedPriceRequest defines model for FeaturedOfferExpectedPriceRequest.
type FeaturedOfferExpectedPriceRequest struct {
	// Embedded struct due to allOf(#/components/schemas/BatchRequest)
	BatchRequest `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/FeaturedOfferExpectedPriceRequestParams)
	FeaturedOfferExpectedPriceRequestParams `yaml:",inline"`
}

// FeaturedOfferExpectedPriceRequestList defines model for FeaturedOfferExpectedPriceRequestList.
type FeaturedOfferExpectedPriceRequestList []FeaturedOfferExpectedPriceRequest

// FeaturedOfferExpectedPriceRequestParams defines model for FeaturedOfferExpectedPriceRequestParams.
type FeaturedOfferExpectedPriceRequestParams struct {

	// The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId MarketplaceId `json:"marketplaceId"`

	// Input segment for featured offer expected price. The segment contains the location information for which featured offer expected price is requested.
	Segment *Segment `json:"segment,omitempty"`

	// The seller SKU of the item.
	Sku Sku `json:"sku"`
}

// FeaturedOfferExpectedPriceResponse defines model for FeaturedOfferExpectedPriceResponse.
type FeaturedOfferExpectedPriceResponse struct {
	// Embedded struct due to allOf(#/components/schemas/BatchResponse)
	BatchResponse `yaml:",inline"`
	// Embedded fields due to inline allOf schema

	// The FOEP response data for a requested SKU.
	Body *FeaturedOfferExpectedPriceResponseBody `json:"body,omitempty"`

	// The parameters for an individual request.
	Request FeaturedOfferExpectedPriceRequestParams `json:"request"`
}

// FeaturedOfferExpectedPriceResponseBody defines model for FeaturedOfferExpectedPriceResponseBody.
type FeaturedOfferExpectedPriceResponseBody struct {

	// A list of error responses that are returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// A list of FOEP results for the requested offer.
	FeaturedOfferExpectedPriceResults *FeaturedOfferExpectedPriceResultList `json:"featuredOfferExpectedPriceResults,omitempty"`

	// Identifies an offer from a particular seller for a specified ASIN.
	OfferIdentifier *OfferIdentifier `json:"offerIdentifier,omitempty"`
}

// FeaturedOfferExpectedPriceResponseList defines model for FeaturedOfferExpectedPriceResponseList.
type FeaturedOfferExpectedPriceResponseList []FeaturedOfferExpectedPriceResponse

// FeaturedOfferExpectedPriceResult defines model for FeaturedOfferExpectedPriceResult.
type FeaturedOfferExpectedPriceResult struct {

	// Schema for `currentFeaturedOffer` or `competingFeaturedOffer`.
	CompetingFeaturedOffer *FeaturedOffer `json:"competingFeaturedOffer,omitempty"`

	// Schema for `currentFeaturedOffer` or `competingFeaturedOffer`.
	CurrentFeaturedOffer *FeaturedOffer `json:"currentFeaturedOffer,omitempty"`

	// The item price at or below which the target offer may be featured.
	FeaturedOfferExpectedPrice *FeaturedOfferExpectedPrice `json:"featuredOfferExpectedPrice,omitempty"`

	// The status of the FOEP computation. Possible values include `VALID_FOEP`, `NO_COMPETING_OFFER`, `OFFER_NOT_ELIGIBLE`, `OFFER_NOT_FOUND`, and `ASIN_NOT_ELIGIBLE`. Additional values might be added in the future.
	ResultStatus string `json:"resultStatus"`
}

// FeaturedOfferExpectedPriceResultList defines model for FeaturedOfferExpectedPriceResultList.
type FeaturedOfferExpectedPriceResultList []FeaturedOfferExpectedPriceResult

// FeaturedOfferSegment defines model for FeaturedOfferSegment.
type FeaturedOfferSegment struct {

	// The customer membership type that makes up this segment
	CustomerMembership string `json:"customerMembership"`

	// The details about the segment. The FeaturedOfferExpectedPrice API uses only the sampleLocation portion as input.
	SegmentDetails SegmentDetails `json:"segmentDetails"`
}

// FulfillmentType defines model for FulfillmentType.
type FulfillmentType string

// List of FulfillmentType
const (
	FulfillmentType_AFN FulfillmentType = "AFN"
	FulfillmentType_MFN FulfillmentType = "MFN"
)

// GetFeaturedOfferExpectedPriceBatchRequest defines model for GetFeaturedOfferExpectedPriceBatchRequest.
type GetFeaturedOfferExpectedPriceBatchRequest struct {

	// A batched list of FOEP requests.
	Requests *FeaturedOfferExpectedPriceRequestList `json:"requests,omitempty"`
}

// GetFeaturedOfferExpectedPriceBatchResponse defines model for GetFeaturedOfferExpectedPriceBatchResponse.
type GetFeaturedOfferExpectedPriceBatchResponse struct {

	// A batched list of FOEP responses.
	Responses *FeaturedOfferExpectedPriceResponseList `json:"responses,omitempty"`
}

// HttpBody defines model for HttpBody.
type HttpBody struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HttpHeaders defines model for HttpHeaders.
type HttpHeaders struct {
	AdditionalProperties map[string]string `json:"-"`
}

// HttpMethod defines model for HttpMethod.
type HttpMethod string

// List of HttpMethod
const (
	HttpMethod_DELETE HttpMethod = "DELETE"
	HttpMethod_GET    HttpMethod = "GET"
	HttpMethod_PATCH  HttpMethod = "PATCH"
	HttpMethod_POST   HttpMethod = "POST"
	HttpMethod_PUT    HttpMethod = "PUT"
)

// HttpStatusLine defines model for HttpStatusLine.
type HttpStatusLine struct {

	// The HTTP response reason phrase.
	ReasonPhrase *string `json:"reasonPhrase,omitempty"`

	// The HTTP response status code.
	StatusCode *int `json:"statusCode,omitempty"`
}

// HttpUri defines model for HttpUri.
type HttpUri string

// Item defines model for Item.
type Item struct {

	// The ASIN of the item.
	Asin Asin `json:"asin"`
}

// LowestPricedOffer defines model for LowestPricedOffer.
type LowestPricedOffer struct {

	// The input required for building `LowestPricedOffers` data in the response.
	LowestPricedOffersInput LowestPricedOffersInput `json:"lowestPricedOffersInput"`

	// A list of up to 20 lowest priced offers that match the criteria specified in `lowestPricedOffersInput`.
	Offers []Offer `json:"offers"`
}

// LowestPricedOffersInput defines model for LowestPricedOffersInput.
type LowestPricedOffersInput struct {

	// The condition of the item.
	ItemCondition Condition `json:"itemCondition"`

	// The input parameter specifies the type of offers requested for `LowestPricedOffers`. This applies to `Consumer` and `Business` offers. `Consumer` is the default `offerType`.
	OfferType string `json:"offerType"`
}

// MarketplaceId defines model for MarketplaceId.
type MarketplaceId string

// MoneyType defines model for MoneyType.
type MoneyType struct {

	// The monetary value.
	Amount *float32 `json:"amount,omitempty"`

	// The currency code in ISO 4217 format.
	CurrencyCode *string `json:"currencyCode,omitempty"`
}

// Offer defines model for Offer.
type Offer struct {

	// The condition of the item.
	Condition Condition `json:"condition"`

	// Indicates whether the item is fulfilled by Amazon or by the seller (merchant).
	FulfillmentType FulfillmentType `json:"fulfillmentType"`

	// Currency type and monetary value schema to demonstrate pricing information.
	ListingPrice MoneyType `json:"listingPrice"`

	// The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points.
	Points *Points `json:"points,omitempty"`

	// Amazon Prime details.
	PrimeDetails *PrimeDetails `json:"primeDetails,omitempty"`

	// The seller identifier for the offer.
	SellerId string `json:"sellerId"`

	// A list of shipping options associated with this offer
	ShippingOptions *[]ShippingOption `json:"shippingOptions,omitempty"`

	// The item subcondition of the offer.
	SubCondition *string `json:"subCondition,omitempty"`
}

// OfferIdentifier defines model for OfferIdentifier.
type OfferIdentifier struct {

	// The ASIN of the item.
	Asin Asin `json:"asin"`

	// Indicates whether the item is fulfilled by Amazon or by the seller (merchant).
	FulfillmentType *FulfillmentType `json:"fulfillmentType,omitempty"`

	// The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId MarketplaceId `json:"marketplaceId"`

	// The seller identifier for the offer.
	SellerId *string `json:"sellerId,omitempty"`

	// The seller SKU of the item. This will only be present for the target offer, which belongs to the requesting seller.
	Sku *string `json:"sku,omitempty"`
}

// Points defines model for Points.
type Points struct {

	// Currency type and monetary value schema to demonstrate pricing information.
	PointsMonetaryValue *MoneyType `json:"pointsMonetaryValue,omitempty"`

	// The number of Amazon Points.
	PointsNumber *int32 `json:"pointsNumber,omitempty"`
}

// PostalCode defines model for PostalCode.
type PostalCode struct {

	// Country code value
	CountryCode *string `json:"countryCode,omitempty"`

	// Postal code value
	Value *string `json:"value,omitempty"`
}

// Price defines model for Price.
type Price struct {

	// Currency type and monetary value schema to demonstrate pricing information.
	ListingPrice MoneyType `json:"listingPrice"`

	// The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points.
	Points *Points `json:"points,omitempty"`

	// Currency type and monetary value schema to demonstrate pricing information.
	ShippingPrice *MoneyType `json:"shippingPrice,omitempty"`
}

// PrimeDetails defines model for PrimeDetails.
type PrimeDetails struct {

	// Indicates whether the offer is an Amazon Prime offer.
	Eligibility string `json:"eligibility"`
}

// ReferencePrice defines model for ReferencePrice.
type ReferencePrice struct {

	// Reference price type (e.g., `CompetitivePriceThreshold`, `WasPrice`, `CompetitivePrice`). For definitions, see the [Product Pricing API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
	Name string `json:"name"`

	// Currency type and monetary value schema to demonstrate pricing information.
	Price MoneyType `json:"price"`
}

// SampleLocation defines model for SampleLocation.
type SampleLocation struct {

	// Postal code value with country code
	PostalCode *PostalCode `json:"postalCode,omitempty"`
}

// Segment defines model for Segment.
type Segment struct {

	// The details about the segment. The FeaturedOfferExpectedPrice API uses only the sampleLocation portion as input.
	SegmentDetails *SegmentDetails `json:"segmentDetails,omitempty"`
}

// SegmentDetails defines model for SegmentDetails.
type SegmentDetails struct {

	// The glance view weighted percentage for this segment, which is the glance views for this segment as a percentage of total glance views across all segments for the ASIN. A higher percentage indicates that more Amazon customers receive this offer as the Featured Offer.
	GlanceViewWeightPercentage *float32 `json:"glanceViewWeightPercentage,omitempty"`

	// Information about a location. It uses a postal code to identify the location.
	SampleLocation *SampleLocation `json:"sampleLocation,omitempty"`
}

// SegmentedFeaturedOffer defines model for SegmentedFeaturedOffer.
type SegmentedFeaturedOffer struct {
	// Embedded struct due to allOf(#/components/schemas/Offer)
	Offer `yaml:",inline"`
	// Embedded fields due to inline allOf schema

	// The list of segment information in which the offer is featured.
	FeaturedOfferSegments []FeaturedOfferSegment `json:"featuredOfferSegments"`
}

// ShippingOption defines model for ShippingOption.
type ShippingOption struct {

	// Currency type and monetary value schema to demonstrate pricing information.
	Price MoneyType `json:"price"`

	// The type of shipping option.
	ShippingOptionType interface{} `json:"shippingOptionType"`
}

// SimilarItems defines model for SimilarItems.
type SimilarItems struct {

	// A list of similar items for the specified ASIN `marketplaceId` combination.
	Items *[]Item `json:"items,omitempty"`
}

// Sku defines model for Sku.
type Sku string

// GetCompetitiveSummaryJSONBody defines parameters for GetCompetitiveSummary.
type GetCompetitiveSummaryJSONBody CompetitiveSummaryBatchRequest

// GetFeaturedOfferExpectedPriceBatchJSONBody defines parameters for GetFeaturedOfferExpectedPriceBatch.
type GetFeaturedOfferExpectedPriceBatchJSONBody GetFeaturedOfferExpectedPriceBatchRequest

// GetCompetitiveSummaryRequestBody defines body for GetCompetitiveSummary for application/json ContentType.
type GetCompetitiveSummaryJSONRequestBody GetCompetitiveSummaryJSONBody

// GetFeaturedOfferExpectedPriceBatchRequestBody defines body for GetFeaturedOfferExpectedPriceBatch for application/json ContentType.
type GetFeaturedOfferExpectedPriceBatchJSONRequestBody GetFeaturedOfferExpectedPriceBatchJSONBody

// Getter for additional properties for HttpBody. Returns the specified
// element and whether it was found
func (a HttpBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HttpBody
func (a *HttpBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HttpBody to handle AdditionalProperties
func (a *HttpBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HttpBody to handle AdditionalProperties
func (a HttpBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HttpHeaders. Returns the specified
// element and whether it was found
func (a HttpHeaders) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HttpHeaders
func (a *HttpHeaders) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HttpHeaders to handle AdditionalProperties
func (a *HttpHeaders) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HttpHeaders to handle AdditionalProperties
func (a HttpHeaders) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}
